---
- name: Update apt cache (if older than an hour)
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: Update older packages with a dist upgrade
  apt: upgrade=dist
  sudo: yes
  
- name: Install basics
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - curl
    - git
    - tmux
    - tree
    - unzip
    - vim
    - wget
