---
- name: Ensure .ssh directory exists
  file: path=~/.ssh state=directory

- name: Ensure known_hosts file exists
  command: touch ~/.ssh/known_hosts

# - name: Add Github to known_hosts file
#   lineinfile: dest=~/.ssh/known_hosts regexp=^${item.host} line="${item.line}"
#   with_items:
#     - { "host": "github.com", "line": "github.com,207.97.227.239 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" }

- name: Clone dotfiles repo
  git: repo=https://github.com/iantruslove/.dotfiles.git
       dest=~/.dotfiles
       version=master

# - name: Die
#   command: exit 1

- name: Install dotfiles
  command: bash ~/.dotfiles/bin/dotfiles
